spring.application.name=cliente

server.port = 8081

spring.data.mongodb.uri=mongodb://localhost:27017/java_devops

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration